### ISSUE TITLE
Causes dog to bark?

### ISSUE THREAD

**Issue by kirubakaran** [rfadams/docker-l2tpipsec-vpn#1]
Whenever I run this program, my dog barks. Please fix.
![480746_4613926078290_1312001424_n](https://f.cloud.github.com/assets/7503/1561036/4ae7f516-5023-11e3-8af2-b5fe7d9b9ced.jpg)

**Comment by rfadams** [comment]
Perfect. 

Closing as: wontfix, working as intended. 

Robert
